## \file config.mk
##
## \brief Configurations for the Make build system.
##
## [2010-06-07 11:04:55 (CEST)]
## This is an autogenerated file. Do not edit.
##
## \author Marco Guazzone, &lt;marco.guazzone@mfn.unipmn.it&gt;
##

CPPFLAGS_release+=
CFLAGS_release+=
CXXFLAGS_release+=-I../dcsxx/src -I../boost-ublas -I/home/sguazt/tmp/cvs-prj/boost-trunk
LDFLAGS_release+=
CPPFLAGS_debug+=
CFLAGS_debug+=
CXXFLAGS_debug+=-I../dcsxx/src -I../boost-ublas -I/home/sguazt/tmp/cvs-prj/boost-trunk
LDFLAGS_debug+=
CPPFLAGS_test+=
CFLAGS_test+=
CXXFLAGS_test+=-I../dcsxx/src -I../boost-ublas -I/home/sguazt/tmp/cvs-prj/boost-trunk
LDFLAGS_test+=
CPPFLAGS_xmp+=
CFLAGS_xmp+=
CXXFLAGS_xmp+=-I../dcsxx/src -I../boost-ublas -I/home/sguazt/tmp/cvs-prj/boost-trunk
LDFLAGS_xmp+=
