#!/bin/bash

##
## Shell script for creating configuration include files.
##
## Authors:
##  Marco Guazzone, <marco.guazzone@mfn.unipmn.it>
##

##TODO:
## * we need to check if c++ (or other compiler??) is present


dtnow=$(date +'%F %T (%Z)')
logfile="$0.log"
basedir=$1

CC=${CC:=cc}
CXX=${CXX:=c++}

## Declares user-related variables
USR_CPPFLAGS=
USR_CFLAGS=
USR_CXXFLAGS=
USR_LDFLAGS=


## Format a date
function dcs_format_date()
{
	echo $(date +'%F %T (%Z)')
}


## Initialize log file
function dcs_log_init()
{
	> $logfile
}


## Log an error to the log-file.
function dcs_log_error()
{
	date=$(dcs_format_date)
	echo "ERROR ($date)>> $1" >> $logfile
}


## Log an error to the log-file.
function dcs_log_info()
{
	date=$(dcs_format_date)
	echo "INFO ($date)>> $1" >> $logfile
}


## Log an error to the log-file.
function dcs_log_warn()
{
	date=$(dcs_format_date)
	echo "WARNING ($date)>> $1" >> $logfile
}


## Check if your system has the Boost libraries installed
function dcs_check_boost()
{
	src_temp_file=`mktemp tmp.XXXXXXXXXX`
	out_temp_file=`mktemp tmp.XXXXXXXXXX`
	cat > $src_temp_file <<EOT
#include <boost/version.hpp>

int main(int argc, char* argv[])
{
	return 0;
}
EOT

	compile_test=(`$CXX $CXXFLAGS -x 'c++' -o $out_temp_file $src_temp_file 2>&1 >/dev/null`)
	ret=$?

	rm -f $out_temp_file $src_temp_file

	if [ $ret == 0 ]; then
		echo -n "yes"
	else
		echo -n "no"
	fi
}


## Script starts here

dcs_log_init
dcs_log_info "Starting configuration maker..."

## Control variables
have_boost_bool=
basesrcdir=


## Sanity checks
if [ -z "$basedir" ]; then
	basedir=.
fi
if [ -z "$basesrcdir" ]; then
	basesrcdir=$basedir/src
fi


## Load user-related variables
if [ -e "$basedir/user-config.sh" ]; then
	source "$basedir/user-config.sh"
fi


## Set C/C++ environments
if [ ! -z "$USR_CPPFLAGS" ]; then
	CPPFLAGS="$CFLAGS $USR_CPPFLAGS"
fi
if [ ! -z "$USR_CFLAGS" ]; then
	CFLAGS="$CFLAGS $USR_CFLAGS"
fi
if [ ! -z "$USR_CXXFLAGS" ]; then
	CXXFLAGS="$CXXFLAGS $USR_CXXFLAGS"
fi
if [ ! -z "$USR_LDFLAGS" ]; then
	LDFLAGS="$LDFLAGS $USR_LDFLAGS"
fi


## Check for Boost
have_boost=`dcs_check_boost`
if [ "$have_boost" = "yes" ]; then
	have_boost_bool='true'
else
	have_boost_bool='false'

	dcs_log_error "Wanted Boost but Boost not found."
	found_errors=yes
fi


## Auto-generation of files.

if [ "$found_errors" = "yes" ]; then
	dcs_log_info "Configuration maker has finished."
	dcs_log_error "Exit with errors!"

	echo "There are some errors. Check the $logfile log-file."
	exit 1
fi


# Create base config dir
mkdir -p "$basesrcdir/config"

cat > $basedir/config.mk <<EOT
## \file config.mk
##
## \brief Configurations for the Make build system.
##
## [$dtnow]
## This is an autogenerated file. Do not edit.
##
## \author Marco Guazzone, &lt;marco.guazzone@mfn.unipmn.it&gt;
##

CPPFLAGS_release+=$USR_CPPFLAGS
CFLAGS_release+=$USR_CFLAGS
CXXFLAGS_release+=$USR_CXXFLAGS
LDFLAGS_release+=$USR_LDFLAGS
CPPFLAGS_debug+=$USR_CPPFLAGS
CFLAGS_debug+=$USR_CFLAGS
CXXFLAGS_debug+=$USR_CXXFLAGS
LDFLAGS_debug+=$USR_LDFLAGS
CPPFLAGS_test+=$USR_CPPFLAGS
CFLAGS_test+=$USR_CFLAGS
CXXFLAGS_test+=$USR_CXXFLAGS
LDFLAGS_test+=$USR_LDFLAGS
CPPFLAGS_xmp+=$USR_CPPFLAGS
CFLAGS_xmp+=$USR_CFLAGS
CXXFLAGS_xmp+=$USR_CXXFLAGS
LDFLAGS_xmp+=$USR_LDFLAGS
EOT

dcs_log_info "Configuration maker has finished."
